name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["14.3.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Env
        run: |
          node -v
          npm -v

      - name: Install
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Compile
        run: npm run compile

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Publish
        uses: JCofman/vscodeaction@master
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN
